# PIPELINE DEFINITION
# Name: product-intelligence-full-pipeline
# Description: Pipeline A to Z : Generation -> Parallel Scraping -> Processing -> Ranking -> Training
components:
  comp-for-loop-1:
    dag:
      tasks:
        scraper-task:
          cachingOptions:
            enableCache: true
          componentRef:
            name: comp-scraper-task
          inputs:
            parameters:
              boutique:
                componentInputParameter: pipelinechannel--targets-loop-item
                parameterExpressionSelector: parseJson(string_value)["nom_boutique"]
              category:
                componentInputParameter: pipelinechannel--targets-loop-item
                parameterExpressionSelector: parseJson(string_value)["category"]
              platform:
                componentInputParameter: pipelinechannel--targets-loop-item
                parameterExpressionSelector: parseJson(string_value)["platform"]
              url:
                componentInputParameter: pipelinechannel--targets-loop-item
                parameterExpressionSelector: parseJson(string_value)["url"]
          taskInfo:
            name: Parallel Scraper
    inputDefinitions:
      parameters:
        pipelinechannel--targets:
          parameterType: LIST
        pipelinechannel--targets-loop-item:
          parameterType: STRING
  comp-generator-task:
    executorLabel: exec-generator-task
    outputDefinitions:
      parameters:
        output_list:
          parameterType: LIST
  comp-processor-task:
    executorLabel: exec-processor-task
  comp-ranking-task:
    executorLabel: exec-ranking-task
  comp-scraper-task:
    executorLabel: exec-scraper-task
    inputDefinitions:
      parameters:
        boutique:
          parameterType: STRING
        category:
          parameterType: STRING
        platform:
          parameterType: STRING
        url:
          parameterType: STRING
  comp-scraping-group:
    dag:
      tasks:
        for-loop-1:
          componentRef:
            name: comp-for-loop-1
          inputs:
            parameters:
              pipelinechannel--targets:
                componentInputParameter: targets
          parameterIterator:
            itemInput: pipelinechannel--targets-loop-item
            items:
              inputParameter: pipelinechannel--targets
          taskInfo:
            name: for-loop-1
    inputDefinitions:
      parameters:
        targets:
          parameterType: LIST
  comp-training-task:
    executorLabel: exec-training-task
deploymentSpec:
  executors:
    exec-generator-task:
      container:
        args:
        - src/agents/generator_agent.py
        - --json
        - '{{$.outputs.parameters[''output_list''].output_file}}'
        command:
        - python3
        image: junaiduthman/product-intel-agents:v-7752cf5
    exec-processor-task:
      container:
        args:
        - src/agents/processor_agent.py
        command:
        - python3
        env:
        - name: DATA_DIR
          value: /app/data
        image: junaiduthman/product-intel-agents:v-7752cf5
    exec-ranking-task:
      container:
        args:
        - src/agents/ranking_agent.py
        command:
        - python3
        image: junaiduthman/product-intel-agents:v-7752cf5
    exec-scraper-task:
      container:
        args:
        - src/agents/scraper_agent.py
        - --boutique
        - '{{$.inputs.parameters[''boutique'']}}'
        - --url
        - '{{$.inputs.parameters[''url'']}}'
        - --category
        - '{{$.inputs.parameters[''category'']}}'
        - --platform
        - '{{$.inputs.parameters[''platform'']}}'
        command:
        - python3
        env:
        - name: DATA_DIR
          value: /app/data
        image: junaiduthman/product-intel-agents:v-7752cf5
    exec-training-task:
      container:
        args:
        - src/agents/train_price_trend_model.py
        command:
        - python3
        image: junaiduthman/product-intel-agents:v-7752cf5
pipelineInfo:
  description: 'Pipeline A to Z : Generation -> Parallel Scraping -> Processing ->
    Ranking -> Training'
  name: product-intelligence-full-pipeline
root:
  dag:
    tasks:
      generator-task:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-generator-task
        taskInfo:
          name: generator-task
      processor-task:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-processor-task
        dependentTasks:
        - scraping-group
        taskInfo:
          name: processor-task
      ranking-task:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-ranking-task
        dependentTasks:
        - processor-task
        taskInfo:
          name: ranking-task
      scraping-group:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-scraping-group
        dependentTasks:
        - generator-task
        inputs:
          parameters:
            targets:
              taskOutputParameter:
                outputParameterKey: output_list
                producerTask: generator-task
        taskInfo:
          name: scraping-group
      training-task:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-training-task
        dependentTasks:
        - ranking-task
        taskInfo:
          name: training-task
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
---
platforms:
  kubernetes:
    deploymentSpec:
      executors:
        exec-processor-task:
          pvcMount:
          - constant: product-intel-pvc
            mountPath: /app/data
          secretAsEnv:
          - keyToEnv:
            - envVar: MYSQL_HOST
              secretKey: MYSQL_HOST
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_USER
              secretKey: MYSQL_USER
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_PASSWORD
              secretKey: MYSQL_PASSWORD
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_DATABASE
              secretKey: MYSQL_DATABASE
            secretName: product-intel-secrets
        exec-ranking-task:
          secretAsEnv:
          - keyToEnv:
            - envVar: MYSQL_HOST
              secretKey: MYSQL_HOST
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_USER
              secretKey: MYSQL_USER
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_PASSWORD
              secretKey: MYSQL_PASSWORD
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_DATABASE
              secretKey: MYSQL_DATABASE
            secretName: product-intel-secrets
        exec-scraper-task:
          pvcMount:
          - constant: product-intel-pvc
            mountPath: /app/data
          secretAsEnv:
          - keyToEnv:
            - envVar: MYSQL_HOST
              secretKey: MYSQL_HOST
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_USER
              secretKey: MYSQL_USER
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_PASSWORD
              secretKey: MYSQL_PASSWORD
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_DATABASE
              secretKey: MYSQL_DATABASE
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: DEEPSEEK_API_KEY
              secretKey: DEEPSEEK_API_KEY
            secretName: product-intel-secrets
        exec-training-task:
          secretAsEnv:
          - keyToEnv:
            - envVar: MYSQL_HOST
              secretKey: MYSQL_HOST
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_USER
              secretKey: MYSQL_USER
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_PASSWORD
              secretKey: MYSQL_PASSWORD
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: MYSQL_DATABASE
              secretKey: MYSQL_DATABASE
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: HF_TOKEN
              secretKey: HF_TOKEN
            secretName: product-intel-secrets
          - keyToEnv:
            - envVar: HF_REPO_ID
              secretKey: HF_REPO_ID
            secretName: product-intel-secrets
