apiVersion: v1
kind: Secret
metadata:
  name: product-intel-secrets
  namespace: kubeflow
type: Opaque
stringData:
  # Once you run `terraform apply`, Terraform will spit out the `rds_endpoint`.
  # Paste that endpoint here (remove the :3306 part if it has it).
  MYSQL_HOST: "replace this with ur rds endpoint"
  MYSQL_USER: "admin"
  MYSQL_DATABASE: "replace this with ur db name"
  
  # Terraform will also spit out `rds_password`. Paste it here.
  MYSQL_PASSWORD: "replace this with ur db password"
  
  # Your external APIs
  DEEPSEEK_API_KEY: "replace this with ur dee"
  HF_TOKEN: "replace this with ur hf token"
  HF_REPO_ID: "repalce this with the hf repo you want to push the model to "
