apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-intel-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/product-intel"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-intel-pvc
  namespace: kubeflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
